export const data =[
    {"x" : 55.782350,
        "y" : 49.115453,
        "type" : "TrafficLightSignal",
        "status" : "Existence",
        "description" : "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.788315,
        "y" : 49.102763,
        "type" : "TrafficLightSignal",
        "status" :"Existence",
        "description" : "Светофор имеет звуковое сопровождение,а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.788315,
        "y" : 49.102763,
        "type" : "TrafficLightSignal",
        "status" : "Existence",
        "description" : "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.829362,
        "y" : 49.059654,
        "type" : "TrafficLightSignal",
        "status" : "Existence",
        "description" : "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.833733,
        "y" : 49.055211,
        "type" : "Ramp",
        "status" : "Existence",
        "description" : "Пандус",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.832489,
        "y" : 49.061178,
        "type" : "Ramp",
        "status" : "Existence",
        "description" : "Пандус",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.830908,
        "y" : 49.063980,
        "type" : "Ramp",
        "status" : "Existence",
        "description" : "Пандус",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.829248,
        "y" : 49.067458,
        "type" : "Ramp",
        "status" : "Existence",
        "description" : "Пандус",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.832898,
        "y" : 49.064012,
        "type" : "Ramp",
        "status" : "Existence",
        "description" : "Пандус",
        "votes": [],
        "evaluations": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.824485,
        "y" : 49.080834,
        "type" : `Ramp`,
        "status" : "Existence",
        "description" : "Пандус",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {"x" : 55.827590,
        "y" : 49.053620,
        "type" : "Toilet",
        "status" : "Existence",
        "description" : "Обычный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate" : 1,
        "numberVotesToDelete" : 0,
        "createDate": "2023-5-27"},

    {
        "x": 55.830382,
        "y": 49.064193,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.824193,
        "y":  49.073650,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }

    ,
    {
        "x":  55.832272,
        "y":  49.061899,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,

    {
        "x":  55.830902,
        "y":  49.073645,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }

    ,
    {
        "x": 55.828025,
        "y": 49.072518,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.829366,
        "y": 49.078790,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.824234,
        "y": 49.073638,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }

    ,
    {
        "x": 55.822174,
        "y": 49.079165,
        "type": "TrafficLightSignal",
        "status": "Existence",
        "description": "Светофор имеет звуковое сопровождение, а также ускоряется когда остается 10 секунд",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.826330,
        "y": 49.064872,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.828571,
        "y": 49.080912,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный стрёмный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.825161,
        "y": 49.041594,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный нормальный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.825426,
        "y": 49.092284,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный нормальный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.821364,
        "y": 49.092283,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный нормальный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }
    ,
    {
        "x": 55.813200,
        "y": 49.105645,
        "type": "Toilet",
        "status": "Existence",
        "description": "Обычный нормальный туалет",
        "evaluations": [],
        "votes": [],
        "numberVotesToCreate": 1,
        "numberVotesToDelete": 0,
        "createDate": "2023-5-27",
    }]


